"""init schema

Revision ID: aae5779358b8
Revises: 56a98863d19a
Create Date: 2025-08-14 07:53:27.220864+00:00

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'aae5779358b8'
down_revision: Union[str, Sequence[str], None] = '56a98863d19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
